services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: DearAI_BE
    ports:
      - "8082:8081"
    restart: always
    depends_on:
      - mysql

volumes:
  mysql_data: